sudo: required

services:
  - docker

script:
  - docker build -t zhaoqin/docker-shadowsocks .
  - docker network create --subnet=172.20.0.0/16 mynet 
  - docker run -d --name shadowsocks --net mynet --ip 172.20.0.2 -p 1234:1234 zhaoqin/docker-shadowsocks -s 0.0.0.0 -p 1234 -k abcd -m aes-256-cfb

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
